spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost/db_vollmed?createDatabaseIfNotExist=true
spring.datasource.username=user01
spring.datasource.password=winner951

server.error.include-stacktrace=never
